### ISSUE TITLE
[TLC] Capitalize `TLC` to avoid ambiguity with the word `tic`

### ISSUE THREAD

**Issue by harbingerofme** [MagnusMagnuson/RoR2Mods#1]
https://github.com/MagnusMagnuson/RoR2Mods/blob/0d9e5810580c1755f3471641bb3b7ece28998338/TemporaryLunarCoins/TemporaryLunarCoins.cs#L192

The word `tlc_aye` looks very similar to `tic_aye` when ingame, and may lead to confusion as to why the game doesn't start.

**Comment by MagnusMagnuson** [comment]
I added `tic_aye` to also be accepted in a recent update. Do you think it should still be capitalized?

PS: [Blazingdrummer ](https://github.com/blazingdrummer/TemporaryLunarCoins) should be taking over this mod really soon and asked for any suggestions to be directed his way, since he'll be maintaining it.

**Comment by harbingerofme** [comment]
Yes. Mostly because it will make it easier for people to make the connection to "temporary lunar coins". But eith that recent update, this is indeed a non-issue.

**Comment by MagnusMagnuson** [comment]
TLC is deprecated
